#index:
#    path: /
#    controller: App\Controller\DefaultController::index
app_pdf_generate:
    path: '/pdf/generate'
    controller: 'App\Controller\GestionCoursController::generatePdf'
app_cours:
    path: /Courss
    controller: App\Controller\GestionCoursController::coursPage
    


