#index:
#    path: /
#    controller: App\Controller\DefaultController::index
# config/routes.yaml
app_reclamation_index:
    path: /reclamation/
    controller: App\Controller\ReclamationController::index
    